export const data = {
  images: [
    {
      id: 1,
      url: 'assets/avatar/avatar1.jpg',
      alt: 'something',
      name: 'eric',
      skill: 'designer',
      link1: '',
      link2: '',
      link3: '',
    },
    {
      id: 2,
      url: 'assets/avatar/avatar2.jpg',
      alt: 'something',
      name: 'Ali',
      skill: 'designer',
      link1: '',
      link2: '',
      link3: '',
    },
    {
      id: 3,
      url: 'assets/avatar/avatar3.jpg',
      alt: 'something',
      name: 'anna',
      skill: 'designer',
      link1: '',
      link2: '',
      link3: '',
    },
    {
      id: 4,
      url: 'assets/avatar/avatar4.jpg',
      alt: 'something',
      name: 'hammad',
      skill: 'designer',
      link1: '',
      link2: '',
      link3: '',
    },
  ],
};
